name: Wheel build

on:
  release:
    types: [created]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          sudo apt-get install libxml2-dev libxmlsec1-dev libxslt-dev python-dev

      - name: Build wheels
        run: python -m pip wheel -w ./wheelhouse .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.image }}
          path: ./wheelhouse/*.whl
          if-no-files-found: ignore
